name: rl-gym
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - tensorflow
  - jupyterlab
  - pandas
  - matplotlib
  - pillow 
  - imageio
  - seaborn
  - scikit-learn
  - category_encoders
  - xgboost
  - itables
  - pip
  - pip:
    - jupyterlab-vim
    - jupyterlab-lsp
    - gymnasium[classic_control,atari]
    - notebook-intelligence
